# Generated by Django 3.2.4 on 2021-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
            options={
                'db_table': 'backgroundImg',
            },
        ),
    ]
