# Generated by Django 3.2.4 on 2021-09-30 23:39

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backgroundimage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Username')),
                ('company_name', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Company name')),
                ('company_logo', cloudinary.models.CloudinaryField(db_index=True, max_length=255, null=True, verbose_name='Company logo')),
                ('role', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Role')),
                ('generated_background', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='generated background')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('background_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backgroundimage.backgroundimg')),
            ],
            options={
                'db_table': 'userBackground',
            },
        ),
    ]
