# Generated by Django 3.2.4 on 2021-11-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backgroundimage', '0001_initial'),
        ('user', '0003_auto_20211005_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, null=True, verbose_name='User name')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='Company name')),
                ('company_logo', models.ImageField(max_length=140, null=True, upload_to='', verbose_name='Company logo')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Role In Company')),
                ('generated_background', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='generated background')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('background_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='backgroundimage.backgroundimg')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
            ],
            options={
                'db_table': 'userBackground',
            },
        ),
    ]
