# Generated by Django 3.2.4 on 2021-11-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbackground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='generated_background',
            field=models.ImageField(max_length=255, null=True, upload_to='', verbose_name='generated background'),
        ),
    ]
