# Generated by Django 3.2.4 on 2021-11-06 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211005_1829'),
        ('backgroundimage', '0001_initial'),
        ('userbackground', '0002_alter_userbackground_generated_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbackground',
            name='user',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to='user.useraccount'),
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='background_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='backgroundimage.backgroundimg'),
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='generated_background',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='generated background'),
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='role',
            field=models.CharField(max_length=50, null=True, verbose_name='Role In Company'),
        ),
    ]
