# Generated by Django 3.2.4 on 2021-11-06 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211005_1829'),
        ('userbackground', '0003_auto_20211105_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccount'),
        ),
    ]
