# Generated by Django 3.2.4 on 2021-11-06 01:27

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundimage', '0001_initial'),
        ('userbackground', '0004_alter_userbackground_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbackground',
            name='user',
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='background_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='backgroundimage.backgroundimg'),
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='generated_background',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='generated background'),
        ),
        migrations.AlterField(
            model_name='userbackground',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Role In Company'),
        ),
    ]
